/*
 * Copyright (c) 2013 Joris Vink <joris@coders.se>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <sys/param.h>
#include <sys/stat.h>

#include <ctype.h>
#include <err.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int
main(int argc, char *argv[])
{
	struct stat	st;
	ssize_t		len;
	FILE		*hdr;
	char		*ext;
	unsigned char	c[1];
	int		fd, newline, count;

	if (argc != 3)
		exit(1);

	if ((fd = open(argv[1], O_RDONLY)) == -1)
		err(1, "open() %d", errno);
	if ((hdr = fopen("static.h", "a+")) == NULL)
		err(1, "fopen() %d", errno);
	if ((ext = strchr(argv[2], '.')) != NULL)
		*(ext)++ = '\0';
	else
		ext = "";

	if (stat(argv[1], &st) == -1) {
		printf("stat(%s) failed: %d\n", argv[1], errno);
		exit(1);
	}

	printf("/**** AUTO GENERATED BY MAKEFILE - DO NOT TOUCH ****/\n");
	printf("#include <sys/param.h>\n\n");
	printf("u_int8_t static_%s_%s[] = {", ext, argv[2]);

	len = 0;
	count = 0;
	newline = 1;
	for (;;) {
		if (newline) {
			printf("\n\t");
			count = 0;
			newline = 0;
		}

		len = read(fd, c, 1);
		if (len == 0)
			break;

		if (len == -1) {
			printf("read(): %d\n", errno);
			exit(1);
		}

		if (len != 1)
			exit(1);

		printf("0x%02x, ", c[0]);
		if (count++ == 10)
			newline = 1;
	}

	close(fd);

	printf("};\n\n");
	printf("u_int32_t static_len_%s_%s = %ld;\n", ext, argv[2], st.st_size);
	printf("time_t static_mtime_%s_%s = %ld;\n", ext, argv[2], st.st_mtime);

	fprintf(hdr, "extern u_int8_t static_%s_%s[];\n", ext, argv[2]);
	fprintf(hdr, "extern u_int32_t static_len_%s_%s;\n", ext, argv[2]);
	fprintf(hdr, "extern time_t static_mtime_%s_%s;\n", ext, argv[2]);
	fclose(hdr);

	return (0);
}
